name: build

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      id: build
      run:  ./build.sh
    
    - uses: actions/upload-artifact@v4
      if: ${{ failure() && steps.build.outcome == 'failure' }}
      with:
        name: build-log
        path: |
          ./Vendor/*.log
          ./build/scratch*/*/ffmpeg/ffbuild/config.log
          ./build/scratch*/*/mpv/meson-logs/meson-log.txt
    
    - name: package
      run:  ./xcframework.sh && ./createZipFramework.sh

    - uses: actions/upload-artifact@v4
      with:
        name: libmpv-ffmpeg-frameworks.tgz
        path: Framework.tgz
